name: Manual build patch (linux + android)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            clang \
            vim-common \
            unzip \
            wget

      # -------- Android NDK --------
      - name: Download Android NDK r28
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip
          unzip android-ndk-r28-linux.zip
          echo "ANDROID_NDK=$PWD/android-ndk-r28" >> $GITHUB_ENV

      # ------------------ Build Android ------------------
      - name: Build Android arm64 binary
        run: |
          rm -rf build-android
          mkdir build-android
          cd build-android

          cmake ../patch \
            -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-31 \
            -DANDROID_STL=c++_static

          cmake --build . -j$(nproc)
          
          echo "Android build output:"
          ls -la

      # ------------------ Build Linux ------------------
      - name: Build Linux binary
        run: |
          rm -rf build-linux
          mkdir build-linux
          cd build-linux

          cmake ../patch
          make -j$(nproc)
          mv patch patch_linux
          
          echo "Linux build output:"
          ls -la
      # ------------------ Upload artifacts ------------------
      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: patch_linux
          path: build-linux/patch_linux

      - name: Upload Android binary
        uses: actions/upload-artifact@v4
        with:
          name: patch_android
          # Загружаем бинарник Android
          path: build-android/*
